WORDS = [
    # Food & Drink
    "pizza", "coffee", "chocolate", "sushi", "burger", "popcorn",
    "gelato", "sandwich", "pancake", "cookie", "apple", "banana",
    "bread", "cheese", "pasta", "soup", "salad", "steak", "taco",
    # Animals
    "dog", "cat", "elephant", "penguin", "dolphin", "tiger", "rabbit",
    "horse", "shark", "monkey", "owl", "bear", "fox", "duck", "lion",
    # Places
    "beach", "mountain", "forest", "desert", "library", "hospital",
    "school", "airport", "museum", "park", "cinema", "stadium",
    # Objects
    "guitar", "piano", "bicycle", "umbrella", "telescope", "compass",
    "lantern", "mirror", "ladder", "hammer", "candle", "balloon",
    "camera", "clock", "diary", "backpack", "wallet", "phone",
    # Nature
    "rainbow", "volcano", "ocean", "river", "thunder", "tornado",
    "snowflake", "sunset", "cactus", "waterfall", "iceberg",
    # Activities
    "swimming", "dancing", "hiking", "cooking", "painting", "gardening",
    "fishing", "running", "reading", "sleeping", "laughing",
]

# Very similar — same sub-category, nearly interchangeable
WORD_PAIRS_SIMILAR = {
    # Food & Drink
    "pizza": "lasagna",
    "coffee": "tea",
    "chocolate": "caramel",
    "sushi": "sashimi",
    "burger": "hotdog",
    "popcorn": "chips",
    "gelato": "sorbet",
    "sandwich": "wrap",
    "pancake": "waffle",
    "cookie": "brownie",
    "apple": "pear",
    "banana": "mango",
    "bread": "toast",
    "cheese": "butter",
    "pasta": "noodles",
    "soup": "stew",
    "salad": "coleslaw",
    "steak": "ribs",
    "taco": "burrito",
    # Animals
    "dog": "wolf",
    "cat": "lynx",
    "elephant": "rhinoceros",
    "penguin": "puffin",
    "dolphin": "porpoise",
    "tiger": "leopard",
    "rabbit": "hare",
    "horse": "donkey",
    "shark": "barracuda",
    "monkey": "chimpanzee",
    "owl": "eagle",
    "bear": "wolverine",
    "fox": "coyote",
    "duck": "goose",
    "lion": "cheetah",
    # Places
    "beach": "lagoon",
    "mountain": "hill",
    "forest": "jungle",
    "desert": "savanna",
    "library": "bookstore",
    "hospital": "clinic",
    "school": "university",
    "airport": "station",
    "museum": "gallery",
    "park": "garden",
    "cinema": "theater",
    "stadium": "arena",
    # Objects
    "guitar": "ukulele",
    "piano": "keyboard",
    "bicycle": "scooter",
    "umbrella": "raincoat",
    "telescope": "binoculars",
    "compass": "map",
    "lantern": "flashlight",
    "mirror": "lens",
    "ladder": "staircase",
    "hammer": "mallet",
    "candle": "torch",
    "balloon": "kite",
    "camera": "camcorder",
    "clock": "sundial",
    "diary": "notebook",
    "backpack": "suitcase",
    "wallet": "purse",
    "phone": "tablet",
    # Nature
    "rainbow": "aurora",
    "volcano": "geyser",
    "ocean": "sea",
    "river": "stream",
    "thunder": "lightning",
    "tornado": "hurricane",
    "snowflake": "hailstone",
    "sunset": "sunrise",
    "cactus": "succulent",
    "waterfall": "rapids",
    "iceberg": "glacier",
    # Activities
    "swimming": "diving",
    "dancing": "gymnastics",
    "hiking": "trekking",
    "cooking": "baking",
    "painting": "sketching",
    "gardening": "farming",
    "fishing": "hunting",
    "running": "jogging",
    "reading": "writing",
    "sleeping": "meditating",
    "laughing": "smiling",
}

# Somewhat similar — same broad domain, less obvious connection
WORD_PAIRS_SOMEWHAT = {
    # Food & Drink
    "pizza": "bread",
    "coffee": "juice",
    "chocolate": "candy",
    "sushi": "dumpling",
    "burger": "sandwich",
    "popcorn": "pretzel",
    "gelato": "pudding",
    "sandwich": "toast",
    "pancake": "muffin",
    "cookie": "cake",
    "apple": "grape",
    "banana": "coconut",
    "bread": "cracker",
    "cheese": "yogurt",
    "pasta": "rice",
    "soup": "broth",
    "salad": "wrap",
    "steak": "chicken",
    "taco": "flatbread",
    # Animals
    "dog": "cat",
    "cat": "rabbit",
    "elephant": "hippo",
    "penguin": "seal",
    "dolphin": "whale",
    "tiger": "wolf",
    "rabbit": "squirrel",
    "horse": "camel",
    "shark": "crocodile",
    "monkey": "parrot",
    "owl": "bat",
    "bear": "deer",
    "fox": "weasel",
    "duck": "seagull",
    "lion": "jaguar",
    # Places
    "beach": "riverbank",
    "mountain": "valley",
    "forest": "trees",
    "desert": "tundra",
    "library": "school",
    "hospital": "pharmacy",
    "school": "library",
    "airport": "harbor",
    "museum": "archive",
    "park": "meadow",
    "cinema": "concert",
    "stadium": "gym",
    # Objects
    "guitar": "drums",
    "piano": "violin",
    "bicycle": "skateboard",
    "umbrella": "jacket",
    "telescope": "microscope",
    "compass": "ruler",
    "lantern": "lamp",
    "mirror": "glass",
    "ladder": "rope",
    "hammer": "wrench",
    "candle": "lighter",
    "balloon": "bubble",
    "camera": "recorder",
    "clock": "calendar",
    "diary": "book",
    "backpack": "briefcase",
    "wallet": "keychain",
    "phone": "watch",
    # Nature
    "rainbow": "cloud",
    "volcano": "mountain",
    "ocean": "lake",
    "river": "pond",
    "thunder": "rain",
    "tornado": "storm",
    "snowflake": "raindrop",
    "sunset": "twilight",
    "cactus": "shrub",
    "waterfall": "spring",
    "iceberg": "snowball",
    # Activities
    "swimming": "running",
    "dancing": "singing",
    "hiking": "cycling",
    "cooking": "shopping",
    "painting": "drawing",
    "gardening": "cleaning",
    "fishing": "camping",
    "running": "walking",
    "reading": "studying",
    "sleeping": "resting",
    "laughing": "crying",
}

# Random — completely different category
WORD_PAIRS_RANDOM = {
    # Food → nature / activities
    "pizza": "tornado",
    "coffee": "penguin",
    "chocolate": "volcano",
    "sushi": "compass",
    "burger": "rainbow",
    "popcorn": "dolphin",
    "gelato": "glacier",
    "sandwich": "gardening",
    "pancake": "telescope",
    "cookie": "shark",
    "apple": "hammer",
    "banana": "library",
    "bread": "swimming",
    "cheese": "river",
    "pasta": "owl",
    "soup": "bicycle",
    "salad": "thunder",
    "steak": "dancing",
    "taco": "iceberg",
    # Animals → objects / places
    "dog": "piano",
    "cat": "umbrella",
    "elephant": "cinema",
    "penguin": "guitar",
    "dolphin": "library",
    "tiger": "balloon",
    "rabbit": "airport",
    "horse": "candle",
    "shark": "museum",
    "monkey": "clock",
    "owl": "beach",
    "bear": "camera",
    "fox": "stadium",
    "duck": "telescope",
    "lion": "compass",
    # Places → food / activities
    "beach": "chocolate",
    "mountain": "cooking",
    "forest": "icecream",
    "desert": "reading",
    "library": "dolphin",
    "hospital": "balloon",
    "school": "fishing",
    "airport": "cookie",
    "museum": "running",
    "park": "sushi",
    "cinema": "hammer",
    "stadium": "soup",
    # Objects → animals / nature
    "guitar": "elephant",
    "piano": "waterfall",
    "bicycle": "penguin",
    "umbrella": "volcano",
    "telescope": "taco",
    "compass": "bear",
    "lantern": "ocean",
    "mirror": "rabbit",
    "ladder": "thunder",
    "hammer": "dolphin",
    "candle": "forest",
    "balloon": "shark",
    "camera": "dancing",
    "clock": "desert",
    "diary": "swimming",
    "backpack": "lion",
    "wallet": "cactus",
    "phone": "hiking",
    # Nature → food / objects
    "rainbow": "burger",
    "volcano": "diary",
    "ocean": "guitar",
    "river": "pancake",
    "thunder": "bicycle",
    "tornado": "cheese",
    "snowflake": "monkey",
    "sunset": "wallet",
    "cactus": "cinema",
    "waterfall": "steak",
    "iceberg": "laughing",
    # Activities → animals / places
    "swimming": "museum",
    "dancing": "fox",
    "hiking": "soup",
    "cooking": "eagle",
    "painting": "desert",
    "gardening": "shark",
    "fishing": "piano",
    "running": "glacier",
    "reading": "tiger",
    "sleeping": "airport",
    "laughing": "cactus",
}

WORD_PAIRS_BY_LEVEL = {
    "similar": WORD_PAIRS_SIMILAR,
    "somewhat": WORD_PAIRS_SOMEWHAT,
    "random": WORD_PAIRS_RANDOM,
}
