WORDS = [
    # Food & Drink (27 words)
    "pizza", "coffee", "chocolate", "burger", "popcorn", "sandwich", "pancake",
    "cookie", "apple", "banana", "bread", "cheese", "pasta", "soup", "salad",
    "steak", "taco", "cake", "ice cream", "rice", "cereal", "donut", "juice",
    "egg", "candy", "hotdog", "shrimp",

    # Animals (27 words)
    "dog", "cat", "elephant", "penguin", "dolphin", "tiger", "rabbit", "horse",
    "shark", "monkey", "owl", "bear", "fox", "duck", "lion", "cow", "bird",
    "snake", "frog", "wolf", "deer", "spider", "bee", "seal", "parrot", "gorilla",

    # Places (23 words)
    "beach", "mountain", "forest", "desert", "library", "hospital", "school",
    "airport", "museum", "park", "cinema", "stadium", "hotel", "market",
    "restaurant", "zoo", "castle", "office", "gym", "mall", "grassland",

    # Objects (27 words)
    "guitar", "piano", "bicycle", "umbrella", "binoculars", "sunglasses", "lamp",
    "mirror", "ladder", "hammer", "candle", "balloon", "camera", "clock",
    "notebook", "backpack", "wallet", "phone", "chair", "book", "pen", "shoe",
    "hat", "knife", "key", "ring",

    # Nature (13 words)
    "rainbow", "volcano", "ocean", "river", "thunder", "tornado", "snowflake",
    "sunset", "cactus", "waterfall", "iceberg", "cloud", "rain", "wind", "moon",
    "star", "fire",

    # Activities (18 words)
    "swimming", "dancing", "hiking", "cooking", "painting", "gardening", "fishing",
    "running", "reading", "sleeping", "laughing", "driving", "singing", "jumping",
    "writing", "shopping", "climbing", "surfing",
]

# Very similar — same sub-category, nearly interchangeable
WORD_PAIRS_SIMILAR = {
    # Food & Drink
    "pizza": "lasagna",
    "coffee": "tea",
    "chocolate": "caramel",
    "burger": "sandwich",
    "popcorn": "chips",
    "sandwich": "wrap",
    "pancake": "waffle",
    "cookie": "brownie",
    "apple": "pear",
    "banana": "mango",
    "bread": "toast",
    "cheese": "butter",
    "pasta": "noodles",
    "soup": "stew",
    "salad": "coleslaw",
    "steak": "ribs",
    "taco": "burrito",
    "cake": "pie",
    "ice cream": "popsicle",
    "rice": "quinoa",
    "cereal": "oatmeal",
    "donut": "bagel",
    "juice": "smoothie",
    "egg": "tofu",
    "candy": "lollipop",
    "hotdog": "sausage",
    "shrimp": "scallop",

    # Animals
    "dog": "puppy",
    "cat": "kitten",
    "elephant": "rhinoceros",
    "penguin": "seal",
    "dolphin": "whale",
    "tiger": "leopard",
    "rabbit": "hare",
    "horse": "donkey",
    "shark": "piranha",
    "monkey": "gorilla",
    "owl": "eagle",
    "bear": "beaver",
    "fox": "coyote",
    "duck": "goose",
    "lion": "cheetah",
    "cow": "buffalo",
    "bird": "sparrow",
    "snake": "lizard",
    "frog": "toad",
    "wolf": "coyote",
    "deer": "elk",
    "spider": "scorpion",
    "bee": "wasp",
    "seal": "sea lion",
    "parrot": "macaw",
    "gorilla": "orangutan",

    # Places
    "beach": "lagoon",
    "mountain": "hill",
    "forest": "jungle",
    "desert": "dune",
    "library": "bookstore",
    "hospital": "clinic",
    "school": "university",
    "airport": "station",
    "museum": "gallery",
    "park": "garden",
    "cinema": "theater",
    "stadium": "arena",
    "hotel": "motel",
    "market": "bazaar",
    "restaurant": "cafe",
    "zoo": "aquarium",
    "castle": "fortress",
    "office": "workspace",
    "gym": "fitness center",
    "mall": "plaza",
    "grassland": "meadow",

    # Objects
    "guitar": "banjo",
    "piano": "keyboard",
    "bicycle": "scooter",
    "umbrella": "raincoat",
    "binoculars": "telescope",
    "sunglasses": "goggles",
    "lamp": "lantern",
    "mirror": "lens",
    "ladder": "staircase",
    "hammer": "mallet",
    "candle": "torch",
    "balloon": "kite",
    "camera": "camcorder",
    "clock": "sundial",
    "notebook": "journal",
    "backpack": "suitcase",
    "wallet": "purse",
    "phone": "tablet",
    "chair": "stool",
    "book": "magazine",
    "pen": "pencil",
    "shoe": "sneaker",
    "hat": "cap",
    "knife": "fork",
    "key": "lock",
    "ring": "bracelet",

    # Nature
    "rainbow": "prism",
    "volcano": "mountain",
    "ocean": "sea",
    "river": "stream",
    "thunder": "lightning",
    "tornado": "hurricane",
    "snowflake": "snowball",
    "sunset": "sunrise",
    "cactus": "fern",
    "waterfall": "creek",
    "iceberg": "glacier",
    "cloud": "fog",
    "rain": "sleet",
    "wind": "breeze",
    "moon": "planet",
    "star": "meteor",
    "fire": "flame",

    # Activities
    "swimming": "diving",
    "dancing": "ballet",
    "hiking": "trekking",
    "cooking": "baking",
    "painting": "sketching",
    "gardening": "farming",
    "fishing": "hunting",
    "running": "jogging",
    "reading": "writing",
    "sleeping": "napping",
    "laughing": "smiling",
    "driving": "racing",
    "singing": "humming",
    "jumping": "hopping",
    "writing": "typing",
    "shopping": "browsing",
    "climbing": "rappelling",
    "surfing": "skateboarding",
}

# Somewhat similar — same broad domain, less obvious connection
WORD_PAIRS_SOMEWHAT = {
    # Food & Drink
    "pizza": "bread",
    "coffee": "tea",
    "chocolate": "candy",
    "burger": "hotdog",
    "popcorn": "pretzel",
    "sandwich": "toast",
    "pancake": "muffin",
    "cookie": "cake",
    "apple": "grape",
    "banana": "coconut",
    "bread": "cracker",
    "cheese": "yogurt",
    "pasta": "rice",
    "soup": "broth",
    "salad": "wrap",
    "steak": "chicken",
    "taco": "flatbread",
    "cake": "waffle",
    "ice cream": "yogurt",
    "rice": "noodles",
    "cereal": "granola",
    "donut": "pastry",
    "juice": "cider",
    "egg": "milk",
    "candy": "chocolate",
    "hotdog": "sausage",
    "shrimp": "crab",

    # Animals
    "dog": "cat",
    "cat": "rabbit",
    "elephant": "hippo",
    "penguin": "puffin",
    "dolphin": "shark",
    "tiger": "wolf",
    "rabbit": "squirrel",
    "horse": "camel",
    "shark": "crocodile",
    "monkey": "chimpanzee",
    "owl": "bat",
    "bear": "deer",
    "fox": "weasel",
    "duck": "seagull",
    "lion": "jaguar",
    "cow": "goat",
    "bird": "butterfly",
    "snake": "cat",
    "frog": "salamander",
    "wolf": "dog",
    "deer": "moose",
    "spider": "insect",
    "bee": "butterfly",
    "seal": "walrus",
    "parrot": "raven",
    "gorilla": "chimpanzee",

    # Places
    "beach": "riverbank",
    "mountain": "valley",
    "forest": "trees",
    "desert": "marsh",
    "library": "school",
    "hospital": "pharmacy",
    "school": "library",
    "airport": "harbor",
    "museum": "archive",
    "park": "meadow",
    "cinema": "concert",
    "stadium": "gym",
    "hotel": "inn",
    "market": "store",
    "restaurant": "kitchen",
    "zoo": "sanctuary",
    "castle": "palace",
    "office": "cubicle",
    "gym": "locker room",
    "mall": "boutique",
    "grassland": "field",

    # Objects
    "guitar": "drums",
    "piano": "violin",
    "bicycle": "skateboard",
    "umbrella": "jacket",
    "binoculars": "microscope",
    "sunglasses": "visor",
    "lamp": "lightbulb",
    "mirror": "glass",
    "ladder": "rope",
    "hammer": "wrench",
    "candle": "lighter",
    "balloon": "bubble",
    "camera": "recorder",
    "clock": "calendar",
    "notebook": "book",
    "backpack": "briefcase",
    "wallet": "keychain",
    "phone": "watch",
    "chair": "bench",
    "book": "newspaper",
    "pen": "marker",
    "shoe": "boot",
    "hat": "helmet",
    "knife": "spoon",
    "key": "latch",
    "ring": "necklace",

    # Nature
    "rainbow": "cloud",
    "volcano": "crater",
    "ocean": "lake",
    "river": "pond",
    "thunder": "rain",
    "tornado": "storm",
    "snowflake": "raindrop",
    "sunset": "twilight",
    "cactus": "shrub",
    "waterfall": "spring",
    "iceberg": "snow",
    "cloud": "mist",
    "rain": "drizzle",
    "wind": "gust",
    "moon": "sun",
    "star": "constellation",
    "fire": "lava",

    # Activities
    "swimming": "running",
    "dancing": "singing",
    "hiking": "cycling",
    "cooking": "shopping",
    "painting": "drawing",
    "gardening": "cleaning",
    "fishing": "camping",
    "running": "walking",
    "reading": "studying",
    "sleeping": "resting",
    "laughing": "joking",
    "driving": "parking",
    "singing": "whistling",
    "jumping": "landing",
    "writing": "journaling",
    "shopping": "browsing",
    "climbing": "hiking",
    "surfing": "diving",
}

# Random — completely different category
WORD_PAIRS_RANDOM = {
    # Food → nature / activities / objects / animals
    "pizza": "tornado",
    "coffee": "penguin",
    "chocolate": "volcano",
    "burger": "rainbow",
    "popcorn": "dolphin",
    "sandwich": "gardening",
    "pancake": "telescope",
    "cookie": "shark",
    "apple": "hammer",
    "banana": "library",
    "bread": "swimming",
    "cheese": "river",
    "pasta": "owl",
    "soup": "bicycle",
    "salad": "thunder",
    "steak": "dancing",
    "taco": "iceberg",
    "cake": "volcano",
    "ice cream": "desert",
    "rice": "hiking",
    "cereal": "moon",
    "donut": "sun",
    "juice": "ocean",
    "egg": "nest",
    "candy": "star",
    "hotdog": "grill",
    "shrimp": "coral",

    # Animals → objects / places / nature / activities
    "dog": "piano",
    "cat": "umbrella",
    "elephant": "cinema",
    "penguin": "guitar",
    "dolphin": "library",
    "tiger": "balloon",
    "rabbit": "airport",
    "horse": "candle",
    "shark": "museum",
    "monkey": "clock",
    "owl": "beach",
    "bear": "camera",
    "fox": "stadium",
    "duck": "lake",
    "lion": "compass",
    "cow": "pasture",
    "bird": "nest",
    "snake": "silo",
    "frog": "lily pad",
    "wolf": "forest",
    "deer": "meadow",
    "spider": "web",
    "bee": "flower",
    "seal": "ice",
    "parrot": "tropical",
    "gorilla": "jungle",

    # Places → food / activities / nature / objects
    "beach": "chocolate",
    "mountain": "cooking",
    "forest": "ice cream",
    "desert": "reading",
    "library": "dolphin",
    "hospital": "balloon",
    "school": "fishing",
    "airport": "cookie",
    "museum": "running",
    "park": "picnic",
    "cinema": "hammer",
    "stadium": "soup",
    "hotel": "vacation",
    "market": "fruit",
    "restaurant": "cooking",
    "zoo": "animal",
    "castle": "royalty",
    "office": "desk",
    "gym": "weights",
    "mall": "shopping",
    "grassland": "buffalo",

    # Objects → animals / nature / activities / places
    "guitar": "elephant",
    "piano": "waterfall",
    "bicycle": "penguin",
    "umbrella": "volcano",
    "binoculars": "eagle",
    "sunglasses": "beach",
    "lamp": "ocean",
    "mirror": "rabbit",
    "ladder": "thunder",
    "hammer": "dolphin",
    "candle": "forest",
    "balloon": "shark",
    "camera": "safari",
    "clock": "desert",
    "notebook": "swimming",
    "backpack": "lion",
    "wallet": "cactus",
    "phone": "hiking",
    "chair": "relaxation",
    "book": "library",
    "pen": "writing",
    "shoe": "walking",
    "hat": "sun",
    "knife": "cutting",
    "key": "door",
    "ring": "finger",

    # Nature → food / objects / activities / animals
    "rainbow": "burger",
    "volcano": "notebook",
    "ocean": "guitar",
    "river": "pancake",
    "thunder": "bicycle",
    "tornado": "cheese",
    "snowflake": "monkey",
    "sunset": "wallet",
    "cactus": "cinema",
    "waterfall": "steak",
    "iceberg": "laughter",
    "cloud": "flying",
    "rain": "umbrella",
    "wind": "kite",
    "moon": "night",
    "star": "wish",
    "fire": "warmth",

    # Activities → animals / places / nature / objects
    "swimming": "museum",
    "dancing": "fox",
    "hiking": "soup",
    "cooking": "eagle",
    "painting": "desert",
    "gardening": "shark",
    "fishing": "piano",
    "running": "glacier",
    "reading": "tiger",
    "sleeping": "airport",
    "laughing": "cactus",
    "driving": "highway",
    "singing": "concert",
    "jumping": "trampoline",
    "writing": "pen",
    "shopping": "mall",
    "climbing": "mountain",
    "surfing": "wave",
}

WORD_PAIRS_BY_LEVEL = {
    "similar": WORD_PAIRS_SIMILAR,
    "somewhat": WORD_PAIRS_SOMEWHAT,
    "random": WORD_PAIRS_RANDOM,
}
