WORDS = [
    # Food & Drink (27 words)
    "pizza", "coffee", "chocolate", "burger", "popcorn", "sandwich", "pancake",
    "cookie", "apple", "banana", "bread", "cheese", "pasta", "soup", "salad",
    "steak", "taco", "cake", "ice cream", "rice", "cereal", "donut", "juice",
    "egg", "candy", "hotdog", "shrimp",

    # Animals (27 words)
    "dog", "cat", "elephant", "penguin", "dolphin", "tiger", "rabbit", "horse",
    "shark", "monkey", "owl", "bear", "fox", "duck", "lion", "cow", "bird",
    "snake", "frog", "wolf", "deer", "spider", "bee", "seal", "parrot", "gorilla",

    # Places (23 words)
    "beach", "mountain", "forest", "desert", "library", "hospital", "school",
    "airport", "museum", "park", "cinema", "stadium", "hotel", "market",
    "restaurant", "zoo", "castle", "office", "gym", "mall", "grassland",

    # Objects (27 words)
    "guitar", "piano", "bicycle", "umbrella", "binoculars", "sunglasses", "lamp",
    "mirror", "ladder", "hammer", "candle", "balloon", "camera", "clock",
    "notebook", "backpack", "wallet", "phone", "chair", "book", "pen", "shoe",
    "hat", "knife", "key", "ring",

    # Nature (13 words)
    "rainbow", "volcano", "ocean", "river", "thunder", "tornado", "snowflake",
    "sunset", "cactus", "waterfall", "iceberg", "cloud", "rain", "wind", "moon",
    "star", "fire",

    # Activities (18 words)
    "swimming", "dancing", "hiking", "cooking", "painting", "gardening", "fishing",
    "running", "reading", "sleeping", "laughing", "driving", "singing", "jumping",
    "writing", "shopping", "climbing", "surfing",

    # Tamil Actors (10 words)
    "rajinikanth", "kamalhaasan", "vijay", "ajith", "dhanush",
    "vikram", "suriya", "sivakarthikeyan", "vijaysethupathi", "madhavan",

    # Tamil Actresses (7 words)
    "nayanthara", "trisha", "samantha", "jyothika", "keerthisuresh",
    "saipallavi", "tamannaah",

    # Tamil Movies (10 words)
    "enthiran", "master", "kaithi", "mersal", "ponniyinselvan",
    "anniyan", "asuran", "ghilli", "roja", "jailer",

    # Famous Landmarks (10 words)
    "tajmahal", "eiffeltower", "colosseum", "greatwall", "pyramids",
    "niagarafalls", "bigben", "statueofliberty", "burjkhalifa", "stonehenge",

    # Famous Persons (11 words)
    "einstein", "shakespeare", "napoleon", "cleopatra", "newton",
    "gandhi", "nelsonmandela", "abrahamlincoln", "michelangelo", "beethoven", "mozart",

    # Countries (13 words)
    "india", "france", "japan", "brazil", "australia",
    "germany", "china", "russia", "italy", "spain",
    "canada", "mexico", "egypt",
]

# Very similar — same sub-category, nearly interchangeable
WORD_PAIRS_SIMILAR = {
    # Food & Drink
    "pizza": "lasagna",
    "coffee": "tea",
    "chocolate": "caramel",
    "burger": "sandwich",
    "popcorn": "chips",
    "sandwich": "wrap",
    "pancake": "waffle",
    "cookie": "brownie",
    "apple": "pear",
    "banana": "mango",
    "bread": "toast",
    "cheese": "butter",
    "pasta": "noodles",
    "soup": "stew",
    "salad": "coleslaw",
    "steak": "ribs",
    "taco": "burrito",
    "cake": "pie",
    "ice cream": "popsicle",
    "rice": "quinoa",
    "cereal": "oatmeal",
    "donut": "bagel",
    "juice": "smoothie",
    "egg": "tofu",
    "candy": "lollipop",
    "hotdog": "sausage",
    "shrimp": "scallop",

    # Animals
    "dog": "puppy",
    "cat": "kitten",
    "elephant": "rhinoceros",
    "penguin": "seal",
    "dolphin": "whale",
    "tiger": "leopard",
    "rabbit": "hare",
    "horse": "donkey",
    "shark": "piranha",
    "monkey": "gorilla",
    "owl": "eagle",
    "bear": "beaver",
    "fox": "coyote",
    "duck": "goose",
    "lion": "cheetah",
    "cow": "buffalo",
    "bird": "sparrow",
    "snake": "lizard",
    "frog": "toad",
    "wolf": "coyote",
    "deer": "elk",
    "spider": "scorpion",
    "bee": "wasp",
    "seal": "sea lion",
    "parrot": "macaw",
    "gorilla": "orangutan",

    # Places
    "beach": "lagoon",
    "mountain": "hill",
    "forest": "jungle",
    "desert": "dune",
    "library": "bookstore",
    "hospital": "clinic",
    "school": "university",
    "airport": "station",
    "museum": "gallery",
    "park": "garden",
    "cinema": "theater",
    "stadium": "arena",
    "hotel": "motel",
    "market": "bazaar",
    "restaurant": "cafe",
    "zoo": "aquarium",
    "castle": "fortress",
    "office": "workspace",
    "gym": "fitness center",
    "mall": "plaza",
    "grassland": "meadow",

    # Objects
    "guitar": "banjo",
    "piano": "keyboard",
    "bicycle": "scooter",
    "umbrella": "raincoat",
    "binoculars": "telescope",
    "sunglasses": "goggles",
    "lamp": "lantern",
    "mirror": "lens",
    "ladder": "staircase",
    "hammer": "mallet",
    "candle": "torch",
    "balloon": "kite",
    "camera": "camcorder",
    "clock": "sundial",
    "notebook": "journal",
    "backpack": "suitcase",
    "wallet": "purse",
    "phone": "tablet",
    "chair": "stool",
    "book": "magazine",
    "pen": "pencil",
    "shoe": "sneaker",
    "hat": "cap",
    "knife": "fork",
    "key": "lock",
    "ring": "bracelet",

    # Nature
    "rainbow": "prism",
    "volcano": "mountain",
    "ocean": "sea",
    "river": "stream",
    "thunder": "lightning",
    "tornado": "hurricane",
    "snowflake": "snowball",
    "sunset": "sunrise",
    "cactus": "fern",
    "waterfall": "creek",
    "iceberg": "glacier",
    "cloud": "fog",
    "rain": "sleet",
    "wind": "breeze",
    "moon": "planet",
    "star": "meteor",
    "fire": "flame",

    # Activities
    "swimming": "diving",
    "dancing": "ballet",
    "hiking": "trekking",
    "cooking": "baking",
    "painting": "sketching",
    "gardening": "farming",
    "fishing": "hunting",
    "running": "jogging",
    "reading": "writing",
    "sleeping": "napping",
    "laughing": "smiling",
    "driving": "racing",
    "singing": "humming",
    "jumping": "hopping",
    "writing": "typing",
    "shopping": "browsing",
    "climbing": "rappelling",
    "surfing": "skateboarding",

    # Tamil Actors — paired with another top actor of similar era/stature
    "rajinikanth": "kamalhaasan",
    "kamalhaasan": "rajinikanth",
    "vijay": "ajith",
    "ajith": "vijay",
    "dhanush": "sivakarthikeyan",
    "vikram": "suriya",
    "suriya": "vikram",
    "sivakarthikeyan": "dhanush",
    "vijaysethupathi": "madhavan",
    "madhavan": "vijaysethupathi",

    # Tamil Actresses — paired with actress of similar era/popularity
    "nayanthara": "trisha",
    "trisha": "nayanthara",
    "samantha": "tamannaah",
    "jyothika": "nayanthara",
    "keerthisuresh": "saipallavi",
    "saipallavi": "keerthisuresh",
    "tamannaah": "samantha",

    # Tamil Movies — paired with movie of same actor or same director
    "enthiran": "master",
    "master": "mersal",
    "kaithi": "asuran",
    "mersal": "ghilli",
    "ponniyinselvan": "roja",
    "anniyan": "enthiran",
    "asuran": "kaithi",
    "ghilli": "master",
    "roja": "ponniyinselvan",
    "jailer": "enthiran",

    # Famous Landmarks — paired with landmark of similar type or era
    "tajmahal": "pyramids",
    "eiffeltower": "bigben",
    "colosseum": "greatwall",
    "greatwall": "colosseum",
    "pyramids": "tajmahal",
    "niagarafalls": "stonehenge",
    "bigben": "eiffeltower",
    "statueofliberty": "bigben",
    "burjkhalifa": "eiffeltower",
    "stonehenge": "pyramids",

    # Famous Persons — paired with person of same field or era
    "einstein": "newton",
    "shakespeare": "michelangelo",
    "napoleon": "abrahamlincoln",
    "cleopatra": "napoleon",
    "newton": "einstein",
    "gandhi": "nelsonmandela",
    "nelsonmandela": "gandhi",
    "abrahamlincoln": "napoleon",
    "michelangelo": "beethoven",
    "beethoven": "mozart",
    "mozart": "beethoven",

    # Countries — paired with country in same region
    "india": "china",
    "france": "germany",
    "japan": "china",
    "brazil": "mexico",
    "australia": "canada",
    "germany": "france",
    "china": "japan",
    "russia": "germany",
    "italy": "spain",
    "spain": "italy",
    "canada": "australia",
    "mexico": "brazil",
    "egypt": "india",
}

# Somewhat similar — same broad domain, less obvious connection
WORD_PAIRS_SOMEWHAT = {
    # Food & Drink
    "pizza": "bread",
    "coffee": "tea",
    "chocolate": "candy",
    "burger": "hotdog",
    "popcorn": "pretzel",
    "sandwich": "toast",
    "pancake": "muffin",
    "cookie": "cake",
    "apple": "grape",
    "banana": "coconut",
    "bread": "cracker",
    "cheese": "yogurt",
    "pasta": "rice",
    "soup": "broth",
    "salad": "wrap",
    "steak": "chicken",
    "taco": "flatbread",
    "cake": "waffle",
    "ice cream": "yogurt",
    "rice": "noodles",
    "cereal": "granola",
    "donut": "pastry",
    "juice": "cider",
    "egg": "milk",
    "candy": "chocolate",
    "hotdog": "sausage",
    "shrimp": "crab",

    # Animals
    "dog": "cat",
    "cat": "rabbit",
    "elephant": "hippo",
    "penguin": "puffin",
    "dolphin": "shark",
    "tiger": "wolf",
    "rabbit": "squirrel",
    "horse": "camel",
    "shark": "crocodile",
    "monkey": "chimpanzee",
    "owl": "bat",
    "bear": "deer",
    "fox": "weasel",
    "duck": "seagull",
    "lion": "jaguar",
    "cow": "goat",
    "bird": "butterfly",
    "snake": "cat",
    "frog": "salamander",
    "wolf": "dog",
    "deer": "moose",
    "spider": "insect",
    "bee": "butterfly",
    "seal": "walrus",
    "parrot": "raven",
    "gorilla": "chimpanzee",

    # Places
    "beach": "riverbank",
    "mountain": "valley",
    "forest": "trees",
    "desert": "marsh",
    "library": "school",
    "hospital": "pharmacy",
    "school": "library",
    "airport": "harbor",
    "museum": "archive",
    "park": "meadow",
    "cinema": "concert",
    "stadium": "gym",
    "hotel": "inn",
    "market": "store",
    "restaurant": "kitchen",
    "zoo": "sanctuary",
    "castle": "palace",
    "office": "cubicle",
    "gym": "locker room",
    "mall": "boutique",
    "grassland": "field",

    # Objects
    "guitar": "drums",
    "piano": "violin",
    "bicycle": "skateboard",
    "umbrella": "jacket",
    "binoculars": "microscope",
    "sunglasses": "visor",
    "lamp": "lightbulb",
    "mirror": "glass",
    "ladder": "rope",
    "hammer": "wrench",
    "candle": "lighter",
    "balloon": "bubble",
    "camera": "recorder",
    "clock": "calendar",
    "notebook": "book",
    "backpack": "briefcase",
    "wallet": "keychain",
    "phone": "watch",
    "chair": "bench",
    "book": "newspaper",
    "pen": "marker",
    "shoe": "boot",
    "hat": "helmet",
    "knife": "spoon",
    "key": "latch",
    "ring": "necklace",

    # Nature
    "rainbow": "cloud",
    "volcano": "crater",
    "ocean": "lake",
    "river": "pond",
    "thunder": "rain",
    "tornado": "storm",
    "snowflake": "raindrop",
    "sunset": "twilight",
    "cactus": "shrub",
    "waterfall": "spring",
    "iceberg": "snow",
    "cloud": "mist",
    "rain": "drizzle",
    "wind": "gust",
    "moon": "sun",
    "star": "constellation",
    "fire": "lava",

    # Activities
    "swimming": "running",
    "dancing": "singing",
    "hiking": "cycling",
    "cooking": "shopping",
    "painting": "drawing",
    "gardening": "cleaning",
    "fishing": "camping",
    "running": "walking",
    "reading": "studying",
    "sleeping": "resting",
    "laughing": "joking",
    "driving": "parking",
    "singing": "whistling",
    "jumping": "landing",
    "writing": "journaling",
    "shopping": "browsing",
    "climbing": "hiking",
    "surfing": "diving",

    # Tamil Actors — paired with actor of different era but same industry
    "rajinikanth": "vijay",
    "kamalhaasan": "suriya",
    "vijay": "dhanush",
    "ajith": "vikram",
    "dhanush": "madhavan",
    "vikram": "ajith",
    "suriya": "vijaysethupathi",
    "sivakarthikeyan": "vijay",
    "vijaysethupathi": "dhanush",
    "madhavan": "suriya",

    # Tamil Actresses — same industry, different generation
    "nayanthara": "samantha",
    "trisha": "jyothika",
    "samantha": "nayanthara",
    "jyothika": "samantha",
    "keerthisuresh": "trisha",
    "saipallavi": "tamannaah",
    "tamannaah": "nayanthara",

    # Tamil Movies — same industry, different genre or era
    "enthiran": "ponniyinselvan",
    "master": "kaithi",
    "kaithi": "mersal",
    "mersal": "master",
    "ponniyinselvan": "anniyan",
    "anniyan": "roja",
    "asuran": "roja",
    "ghilli": "enthiran",
    "roja": "jailer",
    "jailer": "ghilli",

    # Famous Landmarks — same fame, different continent
    "tajmahal": "eiffeltower",
    "eiffeltower": "statueofliberty",
    "colosseum": "stonehenge",
    "greatwall": "pyramids",
    "pyramids": "stonehenge",
    "niagarafalls": "burjkhalifa",
    "bigben": "burjkhalifa",
    "statueofliberty": "eiffeltower",
    "burjkhalifa": "bigben",
    "stonehenge": "colosseum",

    # Famous Persons — same fame, different field
    "einstein": "shakespeare",
    "shakespeare": "napoleon",
    "napoleon": "gandhi",
    "cleopatra": "gandhi",
    "newton": "michelangelo",
    "gandhi": "abrahamlincoln",
    "nelsonmandela": "abrahamlincoln",
    "abrahamlincoln": "gandhi",
    "michelangelo": "newton",
    "beethoven": "shakespeare",
    "mozart": "shakespeare",

    # Countries — same fame, different region
    "india": "brazil",
    "france": "japan",
    "japan": "france",
    "brazil": "australia",
    "australia": "india",
    "germany": "russia",
    "china": "brazil",
    "russia": "china",
    "italy": "egypt",
    "spain": "mexico",
    "canada": "france",
    "mexico": "spain",
    "egypt": "italy",
}

# Random — completely different category, no functional or contextual association
# Tamil names/movies are mixed in as imposter words for general words (and vice versa)
# so players have no way to predict what the imposter received
WORD_PAIRS_RANDOM = {
    # Food → Tamil names / unrelated general words
    "pizza": "rajinikanth",
    "coffee": "nayanthara",
    "chocolate": "vijay",
    "burger": "enthiran",
    "popcorn": "trisha",
    "sandwich": "kamalhaasan",
    "pancake": "mersal",
    "cookie": "samantha",
    "apple": "kaithi",
    "banana": "ajith",
    "bread": "ponniyinselvan",
    "cheese": "tamannaah",
    "pasta": "dhanush",
    "soup": "penguin",
    "salad": "airport",
    "steak": "dancing",
    "taco": "iceberg",
    "cake": "bicycle",
    "ice cream": "desert",
    "rice": "spider",
    "cereal": "moon",
    "donut": "library",
    "juice": "bear",
    "egg": "guitar",
    "candy": "star",
    "hotdog": "wolf",
    "shrimp": "painting",

    # Animals → Tamil names / unrelated general words
    "dog": "vijaysethupathi",
    "cat": "suriya",
    "elephant": "ghilli",
    "penguin": "vikram",
    "dolphin": "saipallavi",
    "tiger": "roja",
    "rabbit": "sivakarthikeyan",
    "horse": "jailer",
    "shark": "madhavan",
    "monkey": "jyothika",
    "owl": "asuran",
    "bear": "keerthisuresh",
    "fox": "anniyan",
    "duck": "swimming",
    "lion": "notebook",
    "cow": "reading",
    "bird": "sunset",
    "snake": "mirror",
    "frog": "backpack",
    "wolf": "park",
    "deer": "fire",
    "spider": "river",
    "bee": "running",
    "seal": "gardening",
    "parrot": "cactus",
    "gorilla": "sleeping",

    # Places → Tamil names / unrelated general words
    "beach": "kamalhaasan",
    "mountain": "enthiran",
    "forest": "nayanthara",
    "desert": "vijay",
    "library": "asuran",
    "hospital": "trisha",
    "school": "mersal",
    "airport": "samantha",
    "museum": "ghilli",
    "park": "rajinikanth",
    "cinema": "hammer",
    "stadium": "egg",
    "hotel": "wind",
    "market": "frog",
    "restaurant": "lamp",
    "zoo": "rain",
    "castle": "bee",
    "office": "seal",
    "gym": "sandwich",
    "mall": "snake",
    "grassland": "coffee",

    # Objects → Tamil names / unrelated general words
    "guitar": "vikram",
    "piano": "ponniyinselvan",
    "bicycle": "ajith",
    "umbrella": "roja",
    "binoculars": "kamalhaasan",
    "sunglasses": "vijay",
    "lamp": "saipallavi",
    "mirror": "enthiran",
    "ladder": "dhanush",
    "hammer": "tamannaah",
    "candle": "suriya",
    "balloon": "jailer",
    "camera": "kaithi",
    "clock": "desert",
    "notebook": "shark",
    "backpack": "lion",
    "wallet": "cactus",
    "phone": "deer",
    "chair": "tornado",
    "book": "gorilla",
    "pen": "iceberg",
    "shoe": "forest",
    "hat": "spider",
    "knife": "rainbow",
    "key": "cloud",
    "ring": "bear",

    # Nature → Tamil names / unrelated general words
    "rainbow": "vijaysethupathi",
    "volcano": "trisha",
    "ocean": "rajinikanth",
    "river": "samantha",
    "thunder": "mersal",
    "tornado": "nayanthara",
    "snowflake": "keerthisuresh",
    "sunset": "anniyan",
    "cactus": "cinema",
    "waterfall": "vijay",
    "iceberg": "dog",
    "cloud": "guitar",
    "rain": "tiger",
    "wind": "clock",
    "moon": "hammer",
    "star": "bread",
    "fire": "duck",

    # Activities → Tamil names / unrelated general words
    "swimming": "kamalhaasan",
    "dancing": "ghilli",
    "hiking": "madhavan",
    "cooking": "jyothika",
    "painting": "roja",
    "gardening": "sivakarthikeyan",
    "fishing": "enthiran",
    "running": "nayanthara",
    "reading": "vijaysethupathi",
    "sleeping": "airport",
    "laughing": "river",
    "driving": "penguin",
    "singing": "ladder",
    "jumping": "library",
    "writing": "bear",
    "shopping": "owl",
    "climbing": "camera",
    "surfing": "hospital",

    # Tamil Actors → Tamil movie or actress (cross-subcategory within Tamil)
    "rajinikanth": "asuran",
    "kamalhaasan": "tamannaah",
    "vijay": "keerthisuresh",
    "ajith": "ponniyinselvan",
    "dhanush": "trisha",
    "vikram": "saipallavi",
    "suriya": "mersal",
    "sivakarthikeyan": "nayanthara",
    "vijaysethupathi": "enthiran",
    "madhavan": "ghilli",

    # Tamil Actresses → Tamil actor or movie (cross-subcategory within Tamil)
    "nayanthara": "vikram",
    "trisha": "kaithi",
    "samantha": "ajith",
    "jyothika": "jailer",
    "keerthisuresh": "suriya",
    "saipallavi": "dhanush",
    "tamannaah": "anniyan",

    # Tamil Movies → Tamil actor or actress (cross-subcategory within Tamil)
    "enthiran": "madhavan",
    "master": "saipallavi",
    "kaithi": "samantha",
    "mersal": "sivakarthikeyan",
    "ponniyinselvan": "trisha",
    "anniyan": "madhavan",
    "asuran": "vijaysethupathi",
    "ghilli": "nayanthara",
    "roja": "vikram",
    "jailer": "tamannaah",

    # Famous Landmarks → Tamil names / general words / famous people
    "tajmahal": "rajinikanth",
    "eiffeltower": "pizza",
    "colosseum": "dolphin",
    "greatwall": "nayanthara",
    "pyramids": "vijay",
    "niagarafalls": "dancing",
    "bigben": "kamalhaasan",
    "statueofliberty": "elephant",
    "burjkhalifa": "mersal",
    "stonehenge": "tiger",

    # Famous Persons → Tamil names / countries / general words
    "einstein": "kaithi",
    "shakespeare": "suriya",
    "napoleon": "cookie",
    "cleopatra": "enthiran",
    "newton": "trisha",
    "gandhi": "rainbow",
    "nelsonmandela": "ghilli",
    "abrahamlincoln": "piano",
    "michelangelo": "dhanush",
    "beethoven": "shark",
    "mozart": "nayanthara",

    # Countries → Tamil names / landmarks / general words
    "india": "vijaysethupathi",
    "france": "tamannaah",
    "japan": "mersal",
    "brazil": "rajinikanth",
    "australia": "clock",
    "germany": "roja",
    "china": "banana",
    "russia": "elephant",
    "italy": "kaithi",
    "spain": "guitar",
    "canada": "dancing",
    "mexico": "saipallavi",
    "egypt": "bicycle",
}

WORD_PAIRS_BY_LEVEL = {
    "similar": WORD_PAIRS_SIMILAR,
    "somewhat": WORD_PAIRS_SOMEWHAT,
    "random": WORD_PAIRS_RANDOM,
}
